micronaut:
  server:
    http-version: 2
    host: 0.0.0.0
    ssl:
      enabled: true
      port: ${PORT:8443}
      key-store:
        path: file:conf/secrets/keystore.jks
        password: ${KEYSTORE_PASSWORD:}
      trust-store:
        path: file:conf/secrets/truststore.jks
        password: ${TRUSTSTORE_PASSWORD:}
  application:
    name: jsonserver
netty:
  default:
    allocator:
      max-order: 3
jackson:
  serialization-inclusion: NON_EMPTY
  serialization:
    indent-output: true
oracle:
  database: ${ORACLE_DATABASE}
  ons: ${ORACLE_ONS_NODES:}
  username: ${ORACLE_USERNAME}
  password: ${ORACLE_PASSWORD}
  truststore:
    path: file:conf/secrets/truststore.jks
    password: ${TRUSTSTORE_PASSWORD:}
  wallet:
    path: file:conf/secrets/ons.p12
    password: ${ORACLE_ONS_WALLET_PASSWORD:}
